# Generated by Django 4.2.7 on 2023-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Category', 'Select Category'), ('Vegetable', 'Vegetable'), ('Fruits', 'Fruits'), ('Electronics', 'Electronics'), ('Electricals', 'Electricals'), ('Daily Needs', 'Daily Needs'), ('Medicine', 'Medicine'), ('Dry Fruits', 'Dry Fruits'), ('Stationary', 'Stationary'), ('Cosmetics', 'Cosmetics'), ('Other', 'Other')], default='Category', max_length=50),
        ),
    ]
