# Generated by Django 4.2.7 on 2023-11-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Category', 'Select Category'), ('Vegetable', 'Vegetable'), ('Fruits', 'Fruits'), ('Dry Fruits', 'Dry Fruits'), ('Daily Needs', 'Daily Needs'), ('Stationary', 'Stationary'), ('Medicine', 'Medicine'), ('Fashion', 'Fashion'), ('Cosmetics', 'Cosmetics'), ('Computer & Acces', 'Computer & Acces'), ('Electronics', 'Electronics'), ('Electricals', 'Electricals'), ('Other', 'Other')], default='Category', max_length=50),
        ),
    ]
