# Generated by Django 4.2.7 on 2023-11-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0011_alter_product_decs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_decs',
        ),
    ]
