# Generated by Django 4.2.7 on 2023-11-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0012_remove_product_long_decs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=14)),
                ('desc', models.CharField(default='', max_length=700)),
            ],
        ),
    ]
