# Generated by Django 4.2.7 on 2023-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0013_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
