# Generated by Django 4.2.7 on 2023-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0015_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='add1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='add2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_if',
            new_name='order_id',
        ),
    ]
