# Generated by Django 4.2.7 on 2023-11-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0016_rename_add1_orders_address1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
