# Generated by Django 4.2.7 on 2023-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0017_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
