# Generated by Django 4.2.7 on 2023-11-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0018_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
