# Generated by Django 4.2.7 on 2023-12-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0020_alter_order_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=14)),
                ('qual', models.CharField(max_length=70)),
                ('skill', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=700)),
            ],
        ),
    ]
