# Generated by Django 4.2.7 on 2023-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBhandar', '0021_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='career',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
